# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: wingcompanion
metadata:
  template: wingcompanion@0.1.0
  
# Services to deploy
services:
  api:
    project: ./backend
    language: dotnet
    host: appservice
    # Build configuration
    build:
      commands:
        - dotnet restore
        - dotnet publish --no-restore -c Release -o ./publish
    # Runtime configuration  
    config:
      platform: linux
      runtime: dotnetcore
      version: "8.0"
      
  web:
    project: ./frontend
    language: js
    host: appservice
    # Build configuration
    build:
      commands:
        - npm install
        - npm run build
    # Runtime configuration
    config:
      platform: linux
      runtime: node
      version: "18"
      
# Infrastructure configuration - using simple deployment
infra:
  provider: bicep
  path: ./infra/bicep
  
# Environment configuration
environments:
  dev:
    location: australiaeast
