// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkingApp.Data;

#nullable disable

namespace NetworkingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250711050000_AddEmergencyTable")]
    partial class AddEmergencyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");
#pragma warning restore 612, 618
        }
    }
}
